name: Fail PR Check

on:
  pull_request:

jobs:
  fail-check:
    runs-on: ubuntu-latest
    steps:
      - name: Wait 60 seconds
        run: |
          echo "Waiting 30 seconds before failing..."
          sleep 60

      - name: Always fail
        run: |
          echo "This check fails on purpose"
          exit 1
